DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
      ID INT NOT NULL AUTO_INCREMENT
    , FIRST_NAME VARCHAR (20) NOT NULL
    , LAST_NAME VARCHAR (30) NOT NULL
    , AGE INT NOT NULL
    , UNIQUE UQ_PERSON_1 (FIRST_NAME, LAST_NAME)
    , PRIMARY KEY (ID)
);
